# Generated by Django 3.2.4 on 2021-06-23 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cash', models.FloatField(default=0)),
                ('currency', models.CharField(choices=[('EUR', 'EURO'), ('USD', 'DOLLAR'), ('PLN', 'ZLOTY')], default='PLN', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('cash', models.FloatField()),
                ('jar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jar')),
            ],
        ),
    ]
